spring.application.name=Civic_Citizen_Help_Desk_Boot
server.port=8282

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/civic_citizen_help_desk?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=vedant
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=civiccitizenhelpdesk@gmail.com
spring.mail.password=jdtu aqvb hgdb dlub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
